# DEPRECATED
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: null
  name: binding-app-custom
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  params:
  - name: targetNamespace
    value: {{ .Values.project.managedNamespace }}
  - name: imageRepo
    value: image-registry.openshift-image-registry.svc:5000/{{ .Values.project.managedNamespace }}/quarkus-playground
  - name: imageTag
    value: $(extensions.imgTag)
  - name: tlsVerify
    value: "false"
  - name: dockerFile
    value: "./src/main/docker/Dockerfile.jvm"
  - name: repoName
    value: $(extensions.repoName)
status: {}
