# ExternalSecret: For GH SSH Key
# All namespaces with "gitops.gov/component: cicd" will receive the (External)Secret
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "eso-global-gh"
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: "eso-gh"

  # This is a basic label selector to select the namespaces to deploy ExternalSecrets to.
  # you can read more about them here https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements
  namespaceSelector:
    matchLabels: 
      gitops.gov/component: cicd

  # How often the ClusterExternalSecret should reconcile itself
  # This will decide how often to check and make sure that the ExternalSecrets exist in the matching namespaces
  refreshTime: "15m0s"

  # This is the spec of the ExternalSecrets to be created
  externalSecretSpec:
    refreshInterval: 30m0s
    secretStoreRef:
      name: secretstore-ibm-secretsmanager
      kind: ClusterSecretStore
    target:
      name: ssh-key-github
      creationPolicy: Owner
      template:
        type: kubernetes.io/ssh-auth
        metadata:
          annotations:
            tekton.dev/git-0: github.com
        data:
          ssh-privatekey: '{{`{{ .data.ghkey }}`}}'
    data:
    - secretKey: ghkey
      remoteRef:
        key: 'b8a300b0-56bc-5575-7f1c-c6ca4975cb3c'
