# ExternalSecret: For SonarQube Token
# All namespaces with "gitops.gov/component: cicd" will receive the (External)Secret
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "eso-global-sonarqube"
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: "eso-sonarqube"

  # This is a basic label selector to select the namespaces to deploy ExternalSecrets to.
  # you can read more about them here https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements
  namespaceSelector:
    matchLabels: 
      gitops.gov/component: cicd

  # How often the ClusterExternalSecret should reconcile itself
  # This will decide how often to check and make sure that the ExternalSecrets exist in the matching namespaces
  refreshTime: "15m0s"

  # This is the spec of the ExternalSecrets to be created
  externalSecretSpec:
    refreshInterval: 30m0s
    secretStoreRef:
      name: secretstore-ibm-secretsmanager
      kind: ClusterSecretStore
    target:
      name: sonarqube-token-secret
      creationPolicy: Owner
    data:
    - secretKey: token
      remoteRef:
        key: 'username_password/6d2a3956-b4e9-31cb-a241-9fa474f1cfff'
        property: 'password'
