# ExternalSecret: For GH SSH Key
# All namespaces with "gitops.gov/component: cicd" will receive the (External)Secret
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "eso-global-gh"
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: "eso-gh"

  # This is a basic label selector to select the namespaces to deploy ExternalSecrets to.
  # you can read more about them here https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements
  namespaceSelector:
    matchLabels: 
      gitops.gov/component: cicd

  # How often the ClusterExternalSecret should reconcile itself
  # This will decide how often to check and make sure that the ExternalSecrets exist in the matching namespaces
  refreshTime: "15m0s"

  # This is the spec of the ExternalSecrets to be created
  externalSecretSpec:
    refreshInterval: 1m0s
    secretStoreRef:
      name: secretstore-ibm-secretsmanager
      kind: ClusterSecretStore
    target:
      name: ssh-key-github
      creationPolicy: Owner
      template:
        type: kubernetes.io/ssh-auth
        metadata:
          annotations:
            # to be recognized from Tekton
            tekton.dev/git-0: github.com
          labels:
            # to be recognized from ArgoCD
            argocd.argoproj.io/secret-type: repo-creds
        data:
          # for Tekton
          ssh-privatekey: '{{ .ghkey }}'
          # for ArgoCD
          sshPrivateKey: |
            '{{ .ghkey }}'

          type: git
          url: git@github.com:haf-tech
    data:
    - secretKey: ghkey
      remoteRef:
        key: 'd945f283-084e-5452-3302-3d9259f76d7c'
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: "eso-global-gh-argocd"
spec:
  # The name to be used on the ExternalSecrets
  externalSecretName: "eso-gh-argocd"

  # This is a basic label selector to select the namespaces to deploy ExternalSecrets to.
  # you can read more about them here https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements
  namespaceSelector:
    matchLabels: 
      gitops.gov/component: cicd

  # How often the ClusterExternalSecret should reconcile itself
  # This will decide how often to check and make sure that the ExternalSecrets exist in the matching namespaces
  refreshTime: "15m0s"

  # This is the spec of the ExternalSecrets to be created
  externalSecretSpec:
    refreshInterval: 1m0s
    secretStoreRef:
      name: secretstore-ibm-secretsmanager
      kind: ClusterSecretStore
    target:
      name: ssh-key-github-argocd
      creationPolicy: Owner
      template:
        #type: kubernetes.io/ssh-auth
        metadata:
          labels:
            # to be recognized from ArgoCD
            argocd.argoproj.io/secret-type: repo-creds
        data:
          # for ArgoCD
          type: git
          sshPrivateKey: |
            '{{ .ghkey }}'
            
          url: git@github.com:haf-tech
    data:
    - secretKey: ghkey
      remoteRef:
        key: 'd945f283-084e-5452-3302-3d9259f76d7c'
