# CI Pipeline for CR Push
#
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: ci-pipeline-cr-push
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  params:
  - name: REPO
    type: string
  - name: COMMIT_SHA
    type: string
  - name: TLSVERIFY
    type: string
  - name: BUILD_EXTRA_ARGS
    type: string
  - name: DOCKERFILE
    type: string
  - name: IMAGE
    description: Image url (incl. tag/version) for a internal CR
    type: string
  - name: IMAGE_REMOTE_CR
    description: Image url (incl. tag/version) for a remote CR
    type: string
  - name: GIT_REF
    type: string
  - name: COMMIT_DATE
    type: string
  - name: COMMIT_AUTHOR
    type: string
  - name: COMMIT_MESSAGE
    type: string
  - name: GIT_REPO
    type: string
  - name: GIT_CONFIG_REPO
    type: string
  - name: GIT_CONFIG_REF
    type: string
  - name: MAVEN_GOALS
    type: array
  - name: SONAR_ENABLED
    type: string
    default: "false"
  - name: SONAR_PROJECT_KEY
    type: string
  - name: SONAR_TOKEN_SECRET_NAME
    type: string
  - name: IMAGE_SCAN_ENABLED
    type: string
    default: "true"
  - name: REMOTE_CR_PUSH_ENABLED
    type: string
    description: If tag and push to a remote CR is wanted or not
    default: "true"
  - name: PROMOTE_VERSION_ENABLED
    type: string
    description: If promoting version back to git is wanted
    default: "true"
  tasks:
  # ##################
  # Tag and Push image to remote CR
  - name: tag-push
    params:
    - name: IMAGE_OLD
      value: $(params.IMAGE)
    - name: IMAGE_NEW
      value: $(params.IMAGE_REMOTE_CR)
    taskRef:
      kind: Task
      name: buildah-tag-push
  workspaces:
  - description: This workspace will receive the cloned git repo.
    name: shared-data
  - description: This workspace will hold the Maven Settings (temp dir).
    name: maven-settings
  - description: This workspace will hold the SonarQube Settings (temp dir).
    name: sonar-settings
