apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipelines-service-{{ .Release.Namespace }}-rb
  annotations:
    argocd.argoproj.io/sync-wave: "-80"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-clusterrole
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: {{ .Release.Namespace }}
