apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: ci-template-generic
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
spec:
  params:
  - description: The image tag.
    name: imageTag
  - description: The git branch for this PR.
    name: io.openshift.build.commit.ref
  - description: the specific commit SHA.
    name: io.openshift.build.commit.id
  - description: The date at which the commit was made
    name: io.openshift.build.commit.date
  - description: The name of the github user handle that made the commit
    name: io.openshift.build.commit.author
  - description: The commit message
    name: io.openshift.build.commit.message
  - description: The git repository URL.
    name: common.git.repo.url
  - description: The GitHub repository for this PullRequest.
    name: fullname
  - description: The repository to push built images to.
    name: imageRepo
  - description: The repository name.
    name: repoName
  - description: Enable image repository TLS certification verification.
    name: tlsVerify
  - description: Extra parameters passed for the push command when pushing images.
    name: build_extra_args
  - description: Custom Dockerfile.
    name: dockerFile
    default: "./src/main/docker/Dockerfile.jvm"
  - name: helmValueFile
    description: Helm Value File name
    default: "values.yaml"
  - name: toolchainID
    description: Continuous Delivery Toolchain ID configured in IBM Cloud
  - name: pipeline.cr.push.enabled
    description: Pipeline config, indicate if a push to a remote Container Registry is wanted or not
    default: "false"
  - name: pipeline.cr.push.enabled
    description: Pipeline config, indicate if a push to a remote Container Registry is wanted or not
    default: "false"
  - name: pipeline.cr.namespace
    description: Pipeline config, Container Registry namespace/repository
    default: ""
  - name: buildTool
    description: Specifies which build automation tool should be used
    default: mvn
  - name: buildArgs
    description: Specifies which build arguments should the build tool use
    default: ["-Dmaven.test.skip=false", "-Dquarkus.log.level=ERROR", "-ntp", "clean", "package"]
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      creationTimestamp: null
      name: ci-app-$(uid)
    spec:
      params:
      - name: RUN_ID
        value: $(uid)
      - name: APP_NAME
        value: $(tt.params.repoName)
      - name: REPO
        value: $(tt.params.fullname)
      - name: GIT_REPO
        value: $(tt.params.common.git.repo.url)
      - name: GIT_CONFIG_REPO
        value: {{ .Values.project.git.config.repo | quote}}
      - name: GIT_CONFIG_REF
        value: {{ .Values.project.git.config.branch | quote}}
      - name: TLSVERIFY
        value: $(tt.params.tlsVerify)
      - name: BUILD_EXTRA_ARGS
        value: $(tt.params.build_extra_args)
      - name: DOCKERFILE
        value: $(tt.params.dockerFile)
      - name: IMAGE
        value: $(tt.params.imageRepo)
      - name: IMAGE_VERSION
        value: $(tt.params.io.openshift.build.commit.ref)-$(tt.params.io.openshift.build.commit.id)
        # ToBeOptimized
      - name: IMAGE_REMOTE_CR
        value: "de.icr.io/$(tt.params.pipeline.cr.namespace)/$(tt.params.repoName):$(tt.params.imageTag)"
      - name: BUILD_TOOL
        value: $(tt.params.buildTool)
      - name: BUILD_ARGS
        value: $(tt.params.buildArgs)
      - name: COMMIT_SHA
        value: $(tt.params.io.openshift.build.commit.id)
      - name: GIT_REF
        value: $(tt.params.io.openshift.build.commit.ref)
      - name: COMMIT_DATE
        value: $(tt.params.io.openshift.build.commit.date)
      - name: COMMIT_AUTHOR
        value: $(tt.params.io.openshift.build.commit.author)
      - name: COMMIT_MESSAGE
        value: $(tt.params.io.openshift.build.commit.message)
      - name: SONAR_ENABLED
        value: "true"
      - name: SONAR_PROJECT_KEY
        value: {{ .Values.project.name | quote}}
      - name: SONAR_TOKEN_SECRET_NAME
        value: "sonarqube-token-secret"
      - name: REMOTE_CR_PUSH_ENABLED
        value: $(tt.params.pipeline.cr.push.enabled)
      - name: HELM_VALUE_FILE
        value: $(tt.params.helmValueFile)
      - name: TOOLCHAINID
        value: $(tt.params.toolchainID)
      pipelineRef:
        name: ci-pipeline-general
      serviceAccountName: pipeline
      #taskRunSpecs:
      #- pipelineTaskName: promote-version
      #  taskPodTemplate:
      #    securityContext:
      #      runAsNonRoot: true
      #      runAsUser: 1000
      #      runAsGroup: 0
      #      fsGroup: 0
      workspaces:
      - name: maven-settings
        emptyDir: {}
      - name: sonar-settings
        emptyDir: {}
      - name: temp-workspace
        emptyDir: {}
      - name: reports
        emptyDir: {}
      - name: shared-data
        persistentVolumeClaim:
          #claimName: pipeline-repo-pvc
          claimName: pipeline-repo-rwm-pvc
    status: {}
status: {}
