# Task: yq
# Source: https://github.com/tektoncd/catalog/blob/main/task/yq/0.3/yq.yaml
# v0.3
#
# Enhancements:
# - context dir
---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: promote-version
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Developer Tools
    tekton.dev/tags: git, yq, promotion
    tekton.dev/displayName: "Promote version"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    Promotes a version. Updates the configuration/manifest and push the updated manifest (with version/tag/digest) back to git
  workspaces:
    - name: source
      description: A workspace that contains the file which needs to be altered.
  params:
    - default: ''
      description: 'git revision to checkout (branch, tag, sha, ref…)'
      name: GIT_REVISION
      type: string
    - name: FILES
      type: array
      description: A list of files to execute the expression on. Needs to be relative to the source workspace.
    - name: EXPRESSION
      type: string
      description: The yq expression to apply. Can be used to replace yaml fields.
    - name: YQ_IMAGE
      type: string
      description: The yq image to use.
      #default: docker.io/mikefarah/yq:4.21.1@sha256:7d9b09f45f5df8874bfc4d63b3d00e5b80b0751e0770bdde197c0f5a9b2e487d
      default: "icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.2"
    - name: CONTEXT_DIR
      type: string
      description: Context directory
      default: 'src_manifest'
  steps:
    - name: replace-in-yaml
      image: $(params.YQ_IMAGE)
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      args: ["$(params.FILES[*])"]
      script: |
        #!/bin/sh

        id

        #workDir=$(workspaces.source.path)/yq
        workDir=$(pwd)
        echo "---------------"
        echo $(pwd)
        echo $workDir
        echo "---------------"
        #cp -r $(workspaces.source.path)/$(params.CONTEXT_DIR)/* $workDir
        #chmod -R +w $workDir

        for var in "$@"
        do
            #/usr/bin/yq eval '$(params.EXPRESSION)' -i "$(pwd)/$var" -v
            /usr/bin/yq eval '$(params.EXPRESSION)' -i "$workDir/$var" -v
        done
      securityContext:
        privileged: true
    - name: push-git
      #image: 'docker.io/alpine/git:v2.26.2'
      image: 'icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.2'
      workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
      script: |
        #!/bin/sh

        git config --global user.email "gitops@haddouti.com"
        git config --global user.name "GitOps Pipeline"

        git add "."
        git status
        git commit -m "[ci] Image digest updated"

        git push origin $(params.GIT_REVISION) -v
      securityContext:
        privileged: true
