# AppProject
{{- range .Values.config.projects }}
{{- if .enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "{{ .name }}-prj"
  namespace: {{ .managedNamespace | quote }} 
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  # Project specific roles, by default is no role defined (see the ArgoCD instance)
  # https://argo-cd.readthedocs.io/en/stable/user-guide/projects/#configuring-rbac-with-projects
  roles: 
  - name: read-only
    description: "Read-only privileges to Project {{ .name }}-prj"
    policies:
    - "p, proj:{{ .name }}-prj:read-only, applications, get, {{ .name }}-prj/*, allow"
    #- "p, proj:{{ .name }}-prj:read-only, applications, sync, {{ .name }}-prj/*, allow"
    groups:
    - "{{ .name }}-group"
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  # Ignore the following Kinds, mostly they are generated but not from ArgoCD
  namespaceResourceBlacklist:
  - group: tekton.dev
    kind: TaskRun
  - group: tekton.dev
    kind: PipelineRun
  # Limit the allowed namespaces for this project
  destinations:
    {{- range .namespaces }}
    - namespace: '{{ .namespace }}'
      server: '*'    
    {{- end }}
  # Limit the git repos which are allowed to use this project  
  sourceRepos:
    - '{{ .git.config.repo }}'
    - '{{ .git.code.repo }}'
{{- if eq (.openShift).group2argo true }}
---
# OpenShift Group for OAuth and ArgoCD RBAC
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: "{{ .name }}-group"
users:
  {{- if and .openShift.users }}
  {{- range .openShift.users }}
  - {{ . }}
  {{- end }}
  {{- else }}
  - "dummy@example.com"
  {{- end }}
{{- end }}
{{- end }}
{{- end }}