# ExternalSecret: For SonarQube Token
# All namespaces with "gitops.gov/component: cicd" will receive the (External)Secret
apiVersion: v1
kind: Secret
metadata:
  name: second-repo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ .Values.project.git.config.repo | quote}}